import { Github, ShieldCheck, Globe } from "lucide-react";

export function Footer() {
  const liveUrl = "https://glyph-forge-beryl.vercel.app/";
  const repoUrl =
    import.meta.env.VITE_REPO_URL || "https://github.com/kambojmayan-png/GlyphForge";

  return (
    <footer id="about" className="border-t border-gf-border bg-gf-surface pt-16 pb-12 text-xs text-gf-text-muted">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 flex flex-col gap-12">
        {/* About Section */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="flex flex-col gap-3">
            <h4 className="font-bold text-sm text-gf-text">About GlyphForge</h4>
            <p className="leading-relaxed">
              GlyphForge is a browser-only contribution art planner. It translates text,
              emojis, and symbols into a 7-row pixel matrix and computes the calendar dates
              required to form that visual pattern on your profile graph.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h4 className="font-bold text-sm text-gf-text">A Planner, Not an Automator</h4>
            <p className="leading-relaxed">
              GlyphForge never connects to GitHub or LeetCode, never requests OAuth tokens, and
              never commits or submits on your behalf. You perform the real daily coding work.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h4 className="font-bold text-sm text-gf-text">Privacy & Independence</h4>
            <div className="flex items-center gap-2 text-gf-level-3 font-medium">
              <ShieldCheck className="w-4 h-4 shrink-0" />
              <span>100% Local & Private</span>
            </div>
            <p className="leading-relaxed">
              Everything runs entirely in your browser. Nothing you type or plan ever leaves your device.
              Not affiliated with or endorsed by GitHub or LeetCode.
            </p>
          </div>
        </div>

        {/* Divider & Credits */}
        <div className="pt-8 border-t border-gf-border/60 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-gf-text font-medium">
            <span>Generated by GlyphForge</span>
            <span>•</span>
            <span className="text-gf-text-muted">v1.0.0</span>
          </div>

          <div className="flex items-center gap-6">
            <a
              href={liveUrl}
              target="_blank"
              rel="noreferrer"
              className="flex items-center gap-1.5 hover:text-gf-text transition-colors"
            >
              <Globe className="w-4 h-4 text-gf-level-3" />
              <span>Live Web App</span>
            </a>

            <a
              href="https://opensource.org/licenses/MIT"
              target="_blank"
              rel="noreferrer"
              className="hover:text-gf-text transition-colors"
            >
              MIT License
            </a>

            {repoUrl && (
              <a
                href={repoUrl}
                target="_blank"
                rel="noreferrer"
                className="flex items-center gap-1.5 hover:text-gf-text transition-colors"
              >
                <Github className="w-4 h-4" />
                <span>GitHub Repository</span>
              </a>
            )}
          </div>
        </div>
      </div>
    </footer>
  );
}
